const action={
    GET_SCHEDULE_REQUEST:'GET_SCHEDULE_REQUEST',
    GET_SCHEDULE_REQUEST_SUCCESS:'GET_SCHEDULE_REQUEST_SUCCESS',
    GET_SCHEDULE_REQUEST_FAILED:'GET_SCHEDULE_REQUEST_FAILED',

}

export default action